name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-selenium pytest-django
      - name: Set environment variables
        run: |
            echo "DJANGO_SECRET_KEY=temporarysecretkey" >> $GITHUB_ENV
            echo "DJANGO_DEBUG=True" >> $GITHUB_ENV
      - name: Collect static files
        run: |
          python3 manage.py collectstatic --noinput
      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: Website.settings
        run: |
          python3 manage.py test